language: scala
scala:
   - 2.12.3

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - >
    if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_REPO_SLUG" = "andreas-schroeder/redisks" ]; then
      if [[ $TRAVIS_TAG ]]; then
        ./gradlew bintrayUpload
      fi
    fi